#!/bin/bash
# Claude Quality Guardian
#
# Daily job that uses Claude Opus 4.6 (via Max subscription) to audit
# and improve content that MiniMax generated. Runs at 05:00 UTC when
# MiniMax jobs are quiet.
#
# Claude reads recently created/modified HTML files and:
#   1. Strips any remaining LLM artifacts regex missed
#   2. Fixes awkward phrasing, garbled sentences
#   3. Ensures editorial quality standards
#   4. Reports what it fixed
#
# This is NOT a rewrite — Claude makes surgical fixes to MiniMax output.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCK_FILE="$PROJECT_DIR/logs/claude-quality.lock"
LOG_FILE="$PROJECT_DIR/logs/claude-quality-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$PROJECT_DIR/logs"
cd "$PROJECT_DIR"

log()  { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"; }
warn() { echo "[$(date '+%H:%M:%S')] WARN: $*" | tee -a "$LOG_FILE" >&2; }

# Lock to prevent overlapping runs
exec 9>"$LOCK_FILE"
if ! flock -n 9; then log "Another claude-quality running. Exiting."; exit 0; fi
echo $$ >"$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"; exec 9>&-' EXIT

RUN_START=$(date +%s)
log "=== Claude Quality Guardian (PID $$) ==="

# Find HTML files modified in the last 26 hours (covers daily window + buffer)
REWRITTEN_FILES=$(find "$PROJECT_DIR/library/rewritten" -name '*.html' -mtime -1 2>/dev/null | sort)
WIKIPEDIA_FILES=$(find "$PROJECT_DIR/library/wikipedia" -name '*.html' -mtime -1 2>/dev/null | sort)

REWRITTEN_COUNT=$(echo "$REWRITTEN_FILES" | grep -c '.' || echo 0)
WIKIPEDIA_COUNT=$(echo "$WIKIPEDIA_FILES" | grep -c '.' || echo 0)
TOTAL=$((REWRITTEN_COUNT + WIKIPEDIA_COUNT))

log "Found $TOTAL files modified in last 24h ($REWRITTEN_COUNT articles, $WIKIPEDIA_COUNT wikipedia)"

if [ "$TOTAL" -eq 0 ]; then
    log "No recent files to audit. Exiting."
    exit 0
fi

# Cap at 30 files per run to keep costs reasonable
MAX_FILES=30
ALL_FILES=$(echo -e "${REWRITTEN_FILES}\n${WIKIPEDIA_FILES}" | head -n "$MAX_FILES")
AUDITING=$(echo "$ALL_FILES" | grep -c '.' || echo 0)
log "Auditing $AUDITING files (capped at $MAX_FILES)"

# Build the file list for Claude's prompt
FILE_LIST=""
for f in $ALL_FILES; do
    REL_PATH="${f#$PROJECT_DIR/}"
    FILE_LIST="${FILE_LIST}
- ${REL_PATH}"
done

# Run Claude Code CLI one-shot
# Uses Max subscription (Opus 4.6) — no API key needed
log "Launching Claude Opus 4.6 quality audit..."

claude -p "You are a quality guardian for a curated reading library. Your job is to audit HTML files generated by a local LLM (MiniMax) and fix any quality issues IN PLACE.

FILES TO AUDIT:
${FILE_LIST}

For each file, read it and check for:

1. JSON ARTIFACTS: Any remaining JSON metadata, keys, braces, or escaped JSON that leaked through. Examples: \`{&quot;title&quot;:\`, \`&quot;}}\`, \`\`\`json\`, XML tags like \`&lt;parameter&gt;\`.

2. LLM SELF-REFERENCE: Sentences where the AI talks about itself — \"I should verify\", \"Let me check\", \"My current version\", verification checklists with checkmarks, \"This essay is approximately X words\".

3. GARBLED TEXT: Sentences that don't make sense — truncated mid-word, Chinese/CJK characters in English text, repeated phrases, incoherent transitions.

4. STRUCTURAL ISSUES: Empty paragraphs, orphaned closing tags, duplicate headings, missing Bottom Line sections in article commentary.

For each issue found:
- Fix it by editing the file directly using the Edit tool
- Be SURGICAL — only fix the specific problem, don't rewrite surrounding content
- If a sentence is hopelessly garbled, remove it entirely rather than guessing
- Never add new content — only fix or remove bad content

After auditing all files, output a summary of what you fixed.

IMPORTANT:
- Do NOT rewrite content for style — MiniMax's voice is intentional
- Do NOT add commentary or editorial changes
- Do NOT modify the source-note paragraph in Wikipedia articles
- Only fix clear defects: artifacts, garble, self-reference, structural issues
- If a file is clean, skip it silently" \
    --model opus \
    --allowedTools "Read,Edit,Glob,Grep,Bash(read-only)" \
    2>&1 | tee -a "$LOG_FILE"

EC=${PIPESTATUS[0]}
if [ "$EC" -ne 0 ]; then
    warn "Claude exited with code $EC"
fi

RUN_E=$(( $(date +%s) - RUN_START ))
log "=== Claude Quality Guardian complete ($(( RUN_E/60 ))m $(( RUN_E%60 ))s) ==="
ln -sf "$LOG_FILE" "$PROJECT_DIR/logs/claude-quality-latest.log"
find "$PROJECT_DIR/logs" -name "claude-quality-*.log" -not -name "claude-quality-latest.log" -mtime +7 -delete
