-- Remove curated-out sources from the database.
-- DO NOT RUN without human review. Generated by feat/curate-diverse-sources.
-- Each slug matches a publication removed from content/ingest-all-sources.json.

BEGIN;

-- Preview what will be affected
SELECT id, slug, name FROM app.publications
WHERE slug IN (
  'a16zcrypto',
  'thedailygwei',
  'aliabdaal',
  'vitadao',
  'radreads',
  'moderndatastack',
  'simplicius'
);

-- Delete articles first (FK), then publications.
DELETE FROM app.articles
WHERE publication_id IN (
  SELECT id FROM app.publications WHERE slug IN (
    'a16zcrypto',
    'thedailygwei',
    'aliabdaal',
    'vitadao',
    'radreads',
    'moderndatastack',
    'simplicius'
  )
);

DELETE FROM app.publications
WHERE slug IN (
  'a16zcrypto',
  'thedailygwei',
  'aliabdaal',
  'vitadao',
  'radreads',
  'moderndatastack',
  'simplicius'
);

-- COMMIT;  -- uncomment after reviewing counts
ROLLBACK;
